### ISSUE TITLE
SDK2.9.2 Version: 'DNACenterAPI' object has no attribute 'user_and_roles'

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacentersdk#171]
**Prerequisites**
* [ Y] Have you tested the operation in the API directly?
* [ Y] Do you have the latest SDK version? 2.9.2
* [ Y] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacentersdk/tree/master#compatibility-matrix) before opening an issue.

**Describe the bug**
We are testing the latest sdk for for Catalyst Center Version 2.3.7.6. The SDK Version is: 2.9.2
For user_and_roles modules getting following error message which was working on earlier version 2.3.7.5.

>>> from dnacentersdk import api
>>> dnac = api.DNACenterAPI(username="admin",
...                         base_url="https://10.195.243.53:443",
...                         password="Maglev123",
...                         version='2.3.7.6',
...                         verify=False)

>>> 
>>> dnac.userand_roles
<dnacentersdk.api.v2_3_7_6.user_and_roles.UserandRoles object at 0x10c49bad0>
>>> dnac.user_and_roles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DNACenterAPI' object has no attribute 'user_and_roles'. Did you mean: 'userand_roles'?
>>> 

Looks like the module is incorrectly named to userand_roles in place of user_and_roles

**Expected behavior**
user_and_roles should work.

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Python version:
* SDK version:2.9.2
* OS Version: 

**Additional context**
